# self-host 용

name: erlbbs dialyzer/unittest

on:
  push:
    branches: [ "main" ]
    paths: '**.erl'
  pull_request:
    branches: [ "main" ]
    paths: '**.erl'

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, Linux]

    # macos에서는 github actions에 docker를 쓸 수 없음
    container:
      image: erlang:latest

    steps:
    - uses: actions/checkout@v3
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Run tests
      run: rebar3 do eunit, ct
