# self-host macos 용

name: erlbbs CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, Linux]

    # macos에서는 github actions에 docker를 쓸 수 없음
    container:
      image: erlang:latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: rebar3 do eunit, ct
